### ISSUE TITLE
Comparison or support of elucidated DDPM

### ISSUE THREAD

**Issue by Mut1nyJD** [LuChengTHU/dpm-solver#10]
Tero Karras earlier this year published a sufficient improvement to DDPM https://arxiv.org/abs/2206.00364 which he called elucidated DDPM. Here it already gets very impressive results with as little as 32 sampling steps. How do you think DPM-Solve compares to it? 

And would it provide any benefit at all on top of it?

**Comment by LuChengTHU** [comment]
Hi @Mut1nyJD , thanks for your interest!

The Karras Algorithm 2 is actually equivalent to singlestep DPM-Solver-2. Such equivalence is just a simple algebra for the second-order solver based on the derivations in our DPM-Solver paper.

In fact, [k-diffusion](https://github.com/crowsonkb/k-diffusion) is the first implementation that unifies both Karras Algorithm 2 and singlestep DPM-Solver-2. You can check this repo to get a deeper understanding.

However, Karras Algorithm 2 uses step schedules for sigma_t, which has terrible numerical issues for a small number of steps (e.g. < 20). And their algorithm cannot be used for the data prediction model. 

Thus, in my opinion, DPM-Solver can include Karras Algorithm 2 as a special example, but DPM-Solver provides a more general formulation and is suitable for both noise-pred and data-pred, both 2nd and 3rd-order solvers. I still recommend using DPM-Solver to accelerate the sampling speed.

**Comment by Mut1nyJD** [comment]
Hi @LuChengTHU 

Thank you so much for your very detailed answer and your suggestions. I will have a look into k-diffusion repository. 

The benefit I've been seeing with Karras Algorithm is not only the sampling but also training seems to converge faster as well at least on the few examples I tried so far that's why I was asking. 
But it is good to know you can combine the two and yes I totally get that your approach is far more flexible.

Thanks again!
