### ISSUE TITLE
Some tinny code wrong writing

### ISSUE THREAD

**Issue by xujz18** [LuChengTHU/dpm-solver#11]
In "example_v2/stable-diffusion/ldm/models/diffusion/dpm_solver/sampler.py: Line 5", "from .solver import NoiseScheduleVP, model_wrapper, DPM_Solver" should be "from .dpm_solver import NoiseScheduleVP, model_wrapper, DPM_Solver".

**Comment by LuChengTHU** [comment]
Thanks for pointing it out! fixed in [8053fa6](https://github.com/LuChengTHU/dpm-solver/commit/8053fa60bb3f8c5d6795403fdc9bbe220625abf0)
