### ISSUE TITLE
Minor Error in get_orders_and_timesteps_for_singlestep_solver, TypeError: cumsum() received an invalid combination of arguments 

### ISSUE THREAD

**Issue by ECHO960** [LuChengTHU/dpm-solver#15]
Hi, thanks for releasing your excellent work.
I am using this code on my own diffusion model. when I was trying 'singlestep' + 'time_uniform' , the following error occurs: 

File "xxx/dpm_solver_pytorch.py", line 495, in get_orders_and_timesteps_for_singlestep_solver
 timesteps_outer = self.get_time_steps(skip_type, t_T, t_0, steps, device)[torch.cumsum(torch.tensor([0,] + orders)).to(device)]
TypeError: cumsum() received an invalid combination of arguments - got (Tensor), but expected one of:         
*(Tensor input, int dim, *, torch.dtype dtype, Tensor out)         
*(Tensor input, name dim, *, torch.dtype dtype, Tensor out)

I check the code [dpm_solver_pytorch.py](https://github.com/LuChengTHU/dpm-solver/blob/main/dpm_solver_pytorch.py) at line #495 seems like `torch.cumsum(input, dim) `requires an explicit argument dim=0.
Maybe this is a minor error?

line #495 should be 
` timesteps_outer = self.get_time_steps(skip_type, t_T, t_0, steps, device)[torch.cumsum(torch.tensor([0,] + orders), dim=0).to(device)]`

**Comment by LuChengTHU** [comment]
Sorry for this bug. Fixed in 3ea000b91525374e75b72b28e4c6522b02866f14.
