### ISSUE TITLE
Score model dosen't usse model_wrapper

### ISSUE THREAD

**Issue by C0cytus** [LuChengTHU/dpm-solver#19]
You stated in README that the model_fn's output should be noise for dpm solver. However, the example in example_v2/score_sde_pytorch doesn't use model_wrapper to turn the score into noise. Is it wrong or do I misunderstood something?
   I would appreciate it a lot if you could reply to me.

**Comment by LuChengTHU** [comment]
Hi @C0cytus ,

Actually in Yang Song's implementation of score-sde, the model output is `noise`, not `score`. He used a wrapper function to convert the model output to `score`, and the training procedure is actually "predicting noise".

You can check these functions:

https://github.com/LuChengTHU/dpm-solver/blob/449a192092f5f22587c5310cdedd9b0f59f123c2/example_v2/score_sde_pytorch/models/utils.py#L158  This is Yang Song's wrapper function for `score`.

https://github.com/LuChengTHU/dpm-solver/blob/449a192092f5f22587c5310cdedd9b0f59f123c2/example_v2/score_sde_pytorch/models/utils.py#L129 This is my wrapper function for `noise pred model`.

So actually we use model_wrapper of `noise` for score-sde code base.

**Comment by C0cytus** [comment]
Thanks for your responding.
  Forgive me for not making it clear at first,  actually I want to use  dpm-solver with VESDE. So I still have some questions.
1. Why does  the get_score_fn just return model output in VESDE's case. 
2. Since get_noise_fn doesn't support VESDE now, so I first get score through  get_score_fn. Then use model_wrapper to turn it into noise. Is it right?
