### ISSUE TITLE
Bug: assert for checking the model_type doesn't include "score" type

### ISSUE THREAD

**Issue by sarvghotra** [LuChengTHU/dpm-solver#21]
Assert check in `model_wrapper` ([here](https://github.com/LuChengTHU/dpm-solver/blob/main/dpm_solver_pytorch.py#L340)) throws an error if the `model_type` is "score".

**Comment by LuChengTHU** [comment]
Sorry for the typo. Fixed in 3d31b82a62799e62cbfbb37a109fdef6309f9cd3
