### ISSUE TITLE
only noise after sampling

### ISSUE THREAD

**Issue by victor886** [LuChengTHU/dpm-solver#22]
[ddpm.txt](https://github.com/LuChengTHU/dpm-solver/files/10213930/ddpm.txt)
hi , I work on a job to generate font using tranditional ddpm model (Discrete time).

I followed the steps in my attach file but get only noise after all tries( I get right result from 1000 iterations).  
can you help me to find what is wrong in my code.

Many thanks.

**Comment by victor886** [comment]
https://github.com/zoubohao/DenoisingDiffusionProbabilityModel-ddpm-
this is the base code I referenced. (diffusion without condition)

**Comment by LuChengTHU** [comment]
Hi @victor886 ,

In your code:
```python
sampler = GaussianDiffusionSampler(model, modelConfig["beta_1"], modelConfig["beta_T"], modelConfig["T"]).to(device)

....

model_fn = model_wrapper(
    sampler,
    noise_schedule,
    model_type="noise",  # or "x_start" or "v" or "score"
    # model_kwargs={"content_imgs" : content_imgs},
)
```
You used `sampler` for the `model_wrapper`, which is unsuitable for DPM-Solver. Could you please use `model` in this API? e.g.,
```python
model_fn = model_wrapper(
    model, # use your noise prediction model here
    noise_schedule,
    model_type="noise",  # or "x_start" or "v" or "score"
    # model_kwargs={"content_imgs" : content_imgs},
)
```

**Comment by victor886** [comment]
Thank you very much for your quick response！ and the problem is solved by your solution, and I get good sampes in 128*128 font image generation.
By the way, I found that in higer resolution (eg. 256*256) image denoise task, the solver seems not stable even in 1000 steps: sometimes, the noise in the background exits, and sometimes it can g
enerate quite good samples.
Could you pls give some advices, many thanks!
I paste the my result in attach file.
<img width="1295" alt="256 font super resolution task" src="https://user-images.githubusercontent.com/5119266/207593946-d87ef414-a1ab-439f-b296-38b8434ff06d.png">

**Comment by LuChengTHU** [comment]
Hi @victor886 ,

If your 1000-step still can not generate good samples, I think it might be because your model has not converged yet. Maybe you can try to train your model with a few more iterations.

**Comment by victor886** [comment]
ok . Thanks a lot . I close the issue.
