### ISSUE TITLE
explicitly predict x0 based on xt and trained model

### ISSUE THREAD

**Issue by JunMa11** [LuChengTHU/dpm-solver#27]
Hi @LuChengTHU ,

Thanks for your great work and detailed documents. 

I have difficulty finding the **predicted x0 in the dpmsolver**. Would it be possible for you to point it out?

https://github.com/LuChengTHU/dpm-solver/blob/main/dpm_solver_pytorch.py

From `x_t` to `x_{t-1}`, the mean is actually the weighted sum between `x_t` and predicted `x_0` (based on `x_t`).
Although we can obtain a simpler formula for `x_t-1` by plugging `x_0` into the mean equation (`\mu`),  the predicted `x_0` is very important when solving some inverse problems because we can incorporate reference information by perturbing the predicted `x_0`. For example https://ddrm-ml.github.io/

This is the reason that I want to **find the code of the predicted `x_0`.** Any guidance would be highly appreciated:) 

![image](https://user-images.githubusercontent.com/19947331/218347249-02420ca0-8e7c-4fbd-ab4c-a5e873ffec50.png)

**Comment by LuChengTHU** [comment]
Hi, it's exactly the data prediction model, https://github.com/LuChengTHU/dpm-solver/blob/main/dpm_solver_pytorch.py#L441

**Comment by JunMa11** [comment]
Thank you so much!

**Comment by JunMa11** [comment]
Hi @LuChengTHU ,

Thanks again for your help.

The function `data_prediction_fn` is used for dpmsolver++, which is not used in dpmsolver, right?

https://github.com/LuChengTHU/dpm-solver/blob/3d31b82a62799e62cbfbb37a109fdef6309f9cd3/dpm_solver_pytorch.py#L655-L681

I want to use dpmsolver for unconditional sampling. Specifically, I have trained an unconditional model based on [guided-diffusion](https://github.com/openai/guided-diffusion) (no classifier guidance). The naive DDPM sampling process (e.g., `x_t` to `x_{t-1}`) includes two steps
- predict `x_0` based on `x_t`
- obtain`x_{t-1}` based on the predicted `x_0` and `x_t`

To solve inverse problems based on diffusion models, I will modify the predicted `x_0`. e.g., `new x_0 = Ax_0 + B`.  The `x_{t-1}` will be based on the new `x_0` and `x_t`

My goal is to speed up this sampling process based on dpmsolver. Based on the recommendation, I should use the the 3rd-order solver. 
https://github.com/LuChengTHU/dpm-solver#example-unconditional-sampling-by-dpm-solver

It seems that dpmsolver doesn't explicitly compute the predicted `x_0` for unconditional sampling, right?

https://github.com/LuChengTHU/dpm-solver/blob/3d31b82a62799e62cbfbb37a109fdef6309f9cd3/dpm_solver_pytorch.py#L683-L801

```python
            if solver_type == 'dpmsolver':
                x_t = (
                    (sigma_t / sigma_s) * x
                    - (alpha_t * phi_1) * model_s
                    + (1. / r2) * (alpha_t * phi_2) * (model_s2 - model_s)
                )

```

**Comment by LuChengTHU** [comment]
Hi @JunMa11 

Yes, dpmsolver doesnot explicitly use the data prediction model. But you can also use 3rd-order dpmsolver++ for unconditional sampling, and it can also get a similar performance as dpmsolver.

**Comment by LuChengTHU** [comment]
In my own experience, both dpmsolver++ and dpmsolver can achieve quite good acceleration performance for unconditional sampling. So you can try dpmsolver++ directly :)
