### ISSUE TITLE
dpm_solver_jax.py - AttributeError: 'Array' object has no attribute 'tile' - 

### ISSUE THREAD

**Issue by soten355** [LuChengTHU/dpm-solver#29]
I'm trying to run the dpm_solver_jax.py, but keep getting this error message:

```
Traceback (most recent call last):
... line 1069, in sample
    vec_t = timesteps[0].tile((x.shape[0]))
AttributeError: 'Array' object has no attribute 'tile'
```

Any ideas on how to fix this?

**Comment by soten355** [comment]
Haven't found the fix yet, but found the cause:

DeviceArray.tile for JAX has been depreciated and is now just jax.numpy.tile. However, the new tile function doesn't work the same way as the old one, so major re-coding of the JAX version is needed.

**Comment by LuChengTHU** [comment]
Please check this PR: #31
