### ISSUE TITLE
a complete demo？

### ISSUE THREAD

**Issue by Tigeryang93** [LuChengTHU/dpm-solver#3]
nice job! can provide a complete demo? load a basic diffusion model, and then sample.

**Comment by LuChengTHU** [comment]
Hi @Tigeryang93 , the pytorch example folder is the complete demo for reproducing the experimental results in our paper. We will add more documentations soon.

**Comment by LuChengTHU** [comment]
Hi @Tigeryang93 , I've added an example of stable-diffusion at: https://github.com/LuChengTHU/dpm-solver/tree/main/example_v2/stable-diffusion

I will further add other simple examples.

**Comment by LuChengTHU** [comment]
Hi @Tigeryang93 , dpmsolver has been supported by [Diffusers](https://github.com/huggingface/diffusers) now! You can use the "DPMSolverMultistepScheduler" for DPM-Solver now!

We also provide a very simple demo for using DPM-Solver with the stable-diffusion pipeline: https://huggingface.co/spaces/LuChengTHU/dpmsolver_sdm
