### ISSUE TITLE
How to generate new image?

### ISSUE THREAD

**Issue by Echo-jyt** [LuChengTHU/dpm-solver#32]
Hi teacher Lu.  I am new to pytorch.  I would like  to know how to use dpm-solver in a pre-trained model(DDPM)  to generate new images . Can you show me an example?

**Comment by LuChengTHU** [comment]
Hi @Echo-jyt , sorry for the late. I've updated the example code for DDPM checkpoint: https://github.com/LuChengTHU/dpm-solver/tree/main/examples/ddpm_and_guided-diffusion

**Comment by Echo-jyt** [comment]
> Hi @Echo-jyt , sorry for the late. I've updated the example code for DDPM checkpoint: https://github.com/LuChengTHU/dpm-solver/tree/main/examples/ddpm_and_guided-diffusion

Thank you very much Mr. Lu
