### ISSUE TITLE
Derivation of equation (A.3) in the paper

### ISSUE THREAD

**Issue by luowyang** [LuChengTHU/dpm-solver#34]
In the DPM-Solver (not the ++) paper, Appendix A.3, equation (A.3) mysteriously emerges from nowhere. The DPM-Solver paper cites the SDE paper, "Score-Based Generative Modeling through Stochastic Differential Equations", as the source of that equation, but I find no clue of how it can be derived from the SDE paper. Can you provide some hints or am I missing something?

**Comment by LuChengTHU** [comment]
Sorry for the wrong cite. It should be this paper: "Maximum Likelihood Training of Score-Based Diffusion Models"

If you are interested in maximum likelihood training of diffusion ODEs, please check my another work "Maximum Likelihood Training for Score-Based Diffusion ODEs by High-Order Denoising Score Matching" :)
