### ISSUE TITLE
discrete-time and continuous-time diffusion models

### ISSUE THREAD

**Issue by fido20160817** [LuChengTHU/dpm-solver#37]
what's the definition of discrete-time and continuous-time diffusion models?  how to define them or judge a pre-trained diffusion model is discrete-time or continuous-time?

**Comment by LuChengTHU** [comment]
Discrete-time diffusion models are trained for discrete time steps (e.g. 0 to 999). Continuous-time diffusion models are trained for continuous time steps (e.g. [1e-3, 1]).

**Comment by fido20160817** [comment]
en, for a pre-trained model, from which parameter we can judge whether it is discrete-time or continuous-time?

**Comment by fido20160817** [comment]
is it "noise_schedule"? which can be set to linear, cosine during training

**Comment by LuChengTHU** [comment]
Please check the range of the model's time input.

**Comment by fido20160817** [comment]
I see, thanks! nice work!
