### ISSUE TITLE
how to set parameters when sampling

### ISSUE THREAD

**Issue by fido20160817** [LuChengTHU/dpm-solver#38]
how to set the following parameters in "Example: Classifier Guidance Sampling by DPM-Solver":

# model_kwargs = {...}
# condition = ...
# betas = ....
# classifier = ...
# classifier_kwargs = {...}

 sometimes, **conditon** is included in **model_kwargs**...
and how to set **classifier_kwargs** and **classifier**?
**betas**? (the definition inside the model?)

**Comment by LuChengTHU** [comment]
Please check this example:

https://github.com/LuChengTHU/dpm-solver/blob/fafa2fb855ed63b625c517b4761bcf8d84f20f4b/examples/ddpm_and_guided-diffusion/runners/diffusion.py#L594

and this example:
https://github.com/LuChengTHU/dpm-solver/blob/fafa2fb855ed63b625c517b4761bcf8d84f20f4b/examples/stable-diffusion/ldm/models/diffusion/dpm_solver/sampler.py#L85

**Comment by fido20160817** [comment]
Thanks!
