### ISSUE TITLE
Support for Classifier-free ?

### ISSUE THREAD

**Issue by ZGCTroy** [LuChengTHU/dpm-solver#4]
Thanks for your impressive work and huge contribution !!!
From your README.md, it can be seen that Classifier Guidance has been supported.
It would be greatful if you could support classifier-free guidance, as it is widely used in many famous work.

**Comment by LuChengTHU** [comment]
Hi @ZGCTroy , thanks for the suggestion. We will add the support and demos in October, including the support for latent diffusion models. (e.g. stable-diffusion).

**Comment by LuChengTHU** [comment]
@ZGCTroy Hi, we've supported classifier-free guidance in the model_wrapper function. Please check our newest version.

If you have any other questions, feel free to ask me :)
