### ISSUE TITLE
Is this error at single step 1st-order code?

### ISSUE THREAD

**Issue by shhh0620** [LuChengTHU/dpm-solver#44]
Hi, thanks for your great work.

I try to use your single-step solver with 1st order in score-sde-pytorch.
But I got the error message like:
`File ~/dpm-solver/examples/score_sde_pytorch/notebooks/../dpm_solver.py:1230, in DPM_Solver.sample(self, x, steps, t_start, t_end, order, skip_type, method, lower_order_final, denoise_to_zero, solver_type, atol, rtol, return_intermediate)`
`   1228     timesteps_outer = self.get_time_steps(skip_type=skip_type, t_T=t_T, t_0=t_0, N=K, device=device)`
`   1229 for step, order in enumerate(orders):`
`-> 1230     s, t = timesteps_outer[step], timesteps_outer[step + 1]`
`   1231     timesteps_inner = self.get_time_steps(skip_type=skip_type, t_T=s.item(), t_0=t.item(), N=order, device=device)`
`   1232     lambda_inner = self.noise_schedule.marginal_lambda(timesteps_inner)`
``
`IndexError: index 2 is out of bounds for dimension 0 with size 2`

In your documentation 3.1., you said 
If `order` == 1:
    K = `steps`.

However in your code (dpm-solver/examples/score_sde_pytorch/dpm_solver.py, line 538), the K when the order is 1 is set to 1 like.
`537    elif order == 1:`
`538        K = 1`
Is it error, or is there any problem with my setting?

**Comment by LuChengTHU** [comment]
Hi @shhh0620 ,

Thanks for finding this bug! I'll fixed it soon.

Yes, it should be `K = steps` instead of `K = 1`.

**Comment by LuChengTHU** [comment]
Fixed in 8acf2bb9419165fec8b3ffd01621aa735be5dee3
