### ISSUE TITLE
Wonder you may integrate the dpm-solver to guided diffusion repo: 

### ISSUE THREAD

**Issue by pengwangucla** [LuChengTHU/dpm-solver#45]
Hi Lu, 
Greate work, thanks for sharing the codebase and nice meeting you on ICML
I wonder whether there are any interests for helping integrate DPM to the guided diffusion model with this repo: 

Following the DDIM format. 
https://github.com/CompVis/latent-diffusion/blob/main/ldm/models/diffusion/ddim.py

It would be great helpful for others since it is widely adopted 

Best

**Comment by LuChengTHU** [comment]
Hi @pengwangucla , Thank you for the great suggestion! In fact, it has already been integrated.

 If you want a dpm-solver for the latent-diffusion codebase, you can check this implementation: https://github.com/CompVis/stable-diffusion/tree/main/ldm/models/diffusion/dpm_solver  which is my official PR to the original stable-diffusion codebase (and this codebase shares almost the same codebase with the latent-diffusion).
