### ISSUE TITLE
Multiple Guidance in Sampling?

### ISSUE THREAD

**Issue by LRMbbj** [LuChengTHU/dpm-solver#54]
Thanks for your excellent work!

I am wondering if DPM Solver supports applying multiple guidance techniques simultaneously, such as both Classifier-free guidance and Classifier guidance, or using multiple guidance techniques with varying guided scales.And are there any plans for implementing these features?

**Comment by LuChengTHU** [comment]
Hi @LRMbbj , thanks for this suggestion! Actually integrate these features is quite easy, but I don't want to increase more features to make the code base more messy, and I want to maintain a clean, tiny codebase. You can implement them with your own forks as you wish :)

**Comment by LRMbbj** [comment]
thanks for your reply!
