### ISSUE TITLE
Reproduce the results in Table 3 - Appendix. E

### ISSUE THREAD

**Issue by HanshuYAN** [LuChengTHU/dpm-solver#6]
Dear authors,

I try to reproduce the results in Table3 of Appendix E (the last row, 2.59 (NFE=51)). I download the checkpoint-8-VP-deep-continuous and set the parameters as those in E.3. However, I cannot get the 2.59 results. My result is much higher around 4.1. Besides, I also test the DDPM-checkpoint-14. My result is also very high, >= 5. 

I checked the codes multiple times, but still cannot get the results.... so... if possible, can you upload a complete script (including parameter setting) that produces the result in Table 3, Appendix E ?

Thank you very much.

**Comment by HanshuYAN** [comment]
> Hi @HanshuYAN ,
> 
> How did you compute the FID score? Have you tried to use the first-order DPM-Solver (which is equivalent to DDIM) with 1000 steps? If the results are still bad, I think there may be some bugs.
> 
> And thank you for the suggestion. We indeed have a plan to release the detailed scripts. (Sorry for the delay, we are busy with other projects recently). Hopefully, we will update this repo in Oct. and clean all the demo codes in the camera-ready version of our paper. Feel free to ask other questions :)

Hi,
I compute the FID as that in [/yang-song/score_sde_pytorch]. I think the computation of FID is correct because I got good results with other samplers such as the prob-flow-ODE with RK45 introduced by [/yang-song/score_sde_pytorch]. 

I also try the first-order DPM-solver with 1000 steps, but I still got 5.2 FID for the basic DDPM model. If I use the prob-flow-solver or the ancestral-sampling, I can get around 3.3 FID which is close to the value reported in [/yang-song/score_sde_pytorch].

I don't know where the issues happen.... so, if possible, it would be nice that you upload a complete test script that can reproduce the results in Fig 2(b) where a smaller model is used in comparison to the values in table 3. 

Many thanks!

**Comment by LuChengTHU** [comment]
Hi @HanshuYAN ,

We've released the example code for score_sde (with both JAX version and PyTorch version). Please check our `example_v2` folder.
