### ISSUE TITLE
Compared to a recent work 

### ISSUE THREAD

**Issue by JunMa11** [LuChengTHU/dpm-solver#7]
Dear @LuChengTHU ,

Thanks for sharing the impressive work. 

What is the advantage of DPM-solver compared to this recent work in ICLR 2023 submission?
https://openreview.net/forum?id=Loek7hfb46P

BTW, I very much enjoy this great extension 
https://openreview.net/forum?id=4vGwQqviud5

**Comment by LuChengTHU** [comment]
Hi @JunMa11 , thanks for your interest!

Indeed, DEIS is a concurrent work of DPM-Solver (The dates of the first arxiv submissions of these two papers are very close). However, there are some differences:
    - DPM-Solver is a single-step (Runge-Kutta-like) solver; DEIS is a multistep (Adams–Bashforth-like) solver.
    - DPM-Solver is analytical; DEIS needs further numerical solver for the coefficients.
    - DPM-Solver further proposes an adaptive step size algorithm. (But I believe DEIS can also implement a similar one.)
    - The time steps used in these two solvers are different. But I believe using the same time steps will give a very similar performance.
   
Overall, I think the speedup performance of DPM-Solver and DEIS is very close, despite the analytic / non-analytic difference.

**Comment by JunMa11** [comment]
Hi @JunMa11 ,

Thanks for your insightful comments very much.

Happy national day:)
