### ISSUE TITLE
Is there a diffuser version?

### ISSUE THREAD

**Issue by dingjingzhen** [LuChengTHU/dpm-solver#9]
Is there a diffuser version?

**Comment by LuChengTHU** [comment]
We did not support the diffusers yet. However, I guess it is easy to combine DPM-Solver with diffusers. For example, applying DPM-Solver for stable-diffusion only needs to add this file: https://github.com/LuChengTHU/dpm-solver/tree/main/example_v2/stable-diffusion/ldm/models/diffusion/dpm_solver

**Comment by keturn** [comment]
The catch with 🧨`diffusers` is that their pipelines are written to sample things according to this [Scheduler](https://huggingface.co/docs/diffusers/api/schedulers#api) interface, and that's an interface that doesn't work well with higher-order samplers like these that need to do multiple model evaluations in a single step.

I hope we'll get diffusers to replace this with a better-suited API, but in the meantime it's possible to make yourself a pipeline that passes the model to the dpm-solver sampler. There's one such attempt to do that here: https://github.com/huggingface/diffusers/pull/857 — it needs some help but it has the potential to let you run the implementations of dpm-solver that are in `k-diffusion` against a `diffusers` model.

**Comment by dingjingzhen** [comment]
> We did not support the diffusers yet. However, I guess it is easy to combine DPM-Solver with diffusers. For example, applying DPM-Solver for stable-diffusion only needs to add this file: https://github.com/LuChengTHU/dpm-solver/tree/main/example_v2/stable-diffusion/ldm/models/diffusion/dpm_solver

Very good work, I will try to use it on diffusers for better use

**Comment by LuChengTHU** [comment]
@dingjingzhen I also created a PR for stable-diffusion, and you can see the detailed modification here: https://github.com/CompVis/stable-diffusion/pull/440

**Comment by LuChengTHU** [comment]
> The catch with 🧨`diffusers` is that their pipelines are written to sample things according to this [Scheduler](https://huggingface.co/docs/diffusers/api/schedulers#api) interface, and that's an interface that doesn't work well with higher-order samplers like these that need to do multiple model evaluations in a single step.
> 
> I hope we'll get diffusers to replace this with a better-suited API, but in the meantime it's possible to make yourself a pipeline that passes the model to the dpm-solver sampler. There's one such attempt to do that here: [huggingface/diffusers#857](https://github.com/huggingface/diffusers/pull/857) — it needs some help but it has the potential to let you run the implementations of dpm-solver that are in `k-diffusion` against a `diffusers` model.

Thanks for the help. I will try it.

**Comment by LuChengTHU** [comment]
> Hi @keturn @dingjingzhen, I've created a pull request for diffusers that supports the multistep version DPM-Solver: [huggingface/diffusers#1132](https://github.com/huggingface/diffusers/pull/1132)
> 
> I hope it will be merged soon :)

Thanks to the great efforts of the huggingface team, DPM-Solver has been supported in diffusers! Close this issue now.
